# modgodb database connection config
[MongoDB]
DBURL = "localhost:27017"
DBName = "post"
UserName = "poster"
Password = "123456"
Enable = true
BlockChain = "matic"

[[Tokens]]
TxType = "swapin"
PairID = "eth"
SwapServer = "http://127.0.0.1:11556/rpc"
TokenAddress = "native"
DepositAddress = "0xaF0A46d3700E23a98F38079cE217742c92aa66aC"

[[Tokens]]
TxType = "swapin"
PairID = "usdt"
SwapServer = "http://127.0.0.1:22556/rpc"
TokenAddress = "0x61b8c4d6d28d5f7edadbea5456db3b4f7f836b64"
DepositAddress = "0xbF0A46d3700E23a98F38079cE217742c92Bb66bC"

[[Tokens]]
TxType = "swapin"
PairID = "wETHv2"
SwapServer = "http://127.0.0.1:22557/rpc"
CallByContract = "0x38b1aad678d9f47ae9bcb79bd9e4a5975fe3a2bd"
DepositAddress = "0x13B432914A996b0A48695dF9B2d701edA45FF264"

[[Tokens]]
TxType = "swapout"
PairID = "bsc"
SwapServer = "http://127.0.0.1:33556/rpc"
TokenAddress = "0x71b8c4d7d28d5f7edadbea5457db3b4f7f837b74"

[[Tokens]]
TxType = "swapout"
PairID = "USDTv3"
SwapServer = "http://172.26.142.154:37919/rpc"
CallByContract = "0xd7e413b3a0dc9e0609b087f3cd52d7b47d510742"
TokenAddress = "0x049d68029688eabf473097a2fc38ef61633a3c7a"

[[Tokens]]
TxType = "swapout2"
PairID = "btc"
SwapServer = "http://127.0.0.1:44556/rpc"
TokenAddress = "0x81b8c4d8d28d5f8edadbea5458db3b4f8f838b84"

[[Tokens]]
TxType = "routerswap"
ChainID = "1"
SwapServer = "http://127.0.0.1:55556/rpc"
RouterContract = "0x6b7a87899490ece95443e979ca9485cbe7e71522"
Whitelist = [""]
